### ISSUE TITLE
add spotless plugin

### ISSUE THREAD

**Issue by ghost** [yegor256/cactoos#771]
Contributions will be cleaner and simpler if [spotless](https://github.com/diffplug/spotless/tree/master/plugin-maven) is used

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ashtonhogan[/z](https://www.0crat.com/u/ashtonhogan) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ashtonhogan but we already have Qulice (with Checkstyle inside). What's the benefit?

**Comment by llorllale** [comment]
@ashtonhogan doesn't qulice provide this for us?

**Comment by ashtonhogan** [comment]
`./mvn spotless:apply` fixes most checkstyle issues

**Comment by ashtonhogan** [comment]
done https://github.com/teamed/qulice/issues/876

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@ashtonhogan[/z](https://www.0crat.com/u/ashtonhogan) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@ashtonhogan to be honest, I still don't see the real issue here. The original requirement was "contributions **will be cleaner** if spotless was used", implying they're not clean enough already? Build fails if qulice requirements are not met. If it fails, the contributor needs to make amends.

From the POV of the project, this workflow has served OK so far, so why change it?

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#771` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
